name: "Main"

on:
  workflow_dispatch:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:

  build-job:
    name: "Build"
    needs: [bindgen-job]
    uses: "./.github/workflows/build.yml"
